class PingTestData < ActiveRecord::Base
  attr_accessible :test_time,
                  :source_node_name,
                  :source_ip_address,
                  :source_group,
                  :dest_node_name,
                  :dest_url,
                  :dest_group,
                  :resolution_time,
                  :lost_packets,
                  :send_packets,
                  :lost_packets_no,
                  :delay,
                  :max_delay,
                  :min_delay,
                  :std_delay,
                  :jitter,
                  :max_jitter,
                  :min_jitter,
                  :std_jitter,
                  :dest_ip_address,
                  :dest_nationality,
                  :dest_province,
                  :dest_locale
end
